# RT-Thread building script for component

Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split('''
NXP/LPC15xx/Source/Templates/system_LPC15xx.c
''')
CPPPATH = [cwd + '/NXP/LPC15xx/Include', cwd + '/../CMSIS/Include']
CPPDEFINES = ['']

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
	src += ['NXP/LPC15xx/Source/Templates/GCC/startup_LPC15xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
	src += ['NXP/LPC15xx/Source/Templates/ARM/startup_LPC15xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
	src += ['NXP/LPC15xx/Source/Templates/IAR/startup_LPC15xx.s']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
